### ISSUE TITLE
Add `events` key to component definition.

### ISSUE THREAD

**Issue by jerricco** [SilbinaryWolf/proposal-fel#1]
JavaScript has a [rather nice events system](https://developer.mozilla.org/en-US/docs/Web/Events), and helps with communication between parent and child components.

It would be nice to be able to specify events in a component like so:
``` javascript
events [
    'select', //Use a string for a default (bubbles/cancellable) event
    'set_time',
    {
        name := 'set_date',
        bubbles := false
    }, //Or an object to detail the event
    ....
]
```

Then wherever behaviour is defined*, you can emit an event like so; `element.emit('select', extra)` 
or listen: `element.listen('select', fn)`.

Each event name when actually emitted at runtime should be prepended by the component name and a dot `.`, Eg: `'Button.select'`
If a namespace is set in the build config, maybe that can also be prepended in the same way?

_*Which leads into another question about where behaviour is defined lel. I'll make another issue for this._

**Comment by silbinarywolf** [comment]
What problem would this feature solve?
Why not just write your JavaScript seperately to the component (with the events etc?)

I'm thinking perhaps the "FEL" language will transpile to JS at some point in time, but for now I'm not sure that sort of thing is needed or helpful.

**Comment by jerricco** [comment]
It doesn't seem intuitive to have "FEL" declaratively state everything about a component, but say nothing about its behaviour. Since JS is the only way to invoke behaviour in the DOM, should it not then be tied to the component itself?

Also, since most asset pipelines focus around how the JavaScript is laid out (ie: the logical structure of front-end software), FEL would just become a _separate_ tool to use and integrate into that JS build process (which would likely render a few features of FEL config relatively useless, like some of its Brunch inspired ones).

You simply wouldn't ever want to write all your HTML/CSS as FEL to compile, then tack on some sort of JS that somehow relates to each FEL component. Unless FEL compilation is something that strictly occurs _during_ a JS transpilation/bundling, in which case it would have to compete with certain loaders that allow HTML within JS.

Seems more natural to allow components to be written with behaviour and let FEL be the start of the toolchain (FEL JS compiles down into ES6 or something, which can pass directly to Babel for example).

**Comment by silbinarywolf** [comment]
Discussed this in person and docs have since been updated to state that we're mostly wanting to handle HTML/CSS side of things for now.
